---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warpstream-agent.fullname" . }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if or (.Values.config.playground) (not (hasPrefix "vci_sr_" .Values.config.virtualClusterID)) }}
    - port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
    {{- end }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if or (.Values.config.playground) (hasPrefix "vci_sr_" .Values.config.virtualClusterID) }}
    - port: {{ .Values.service.schemaRegistryPort | default 9094 }}
      targetPort: schema-registry
      protocol: TCP
      name: schema-registry
    {{- end }}
  selector:
    {{- include "warpstream-agent.selectorLabels" . | nindent 4 }}
...
{{- if .Values.service.perPod }}
{{- if and (eq (include "warpstream-agent.deploymentKind" .) "StatefulSet") (.Values.service.perPod.enabled) }}
{{ $replicas := (.Values.replicas | int) }}
{{- range $i, $e := until $replicas }}
{{- with $ }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warpstream-agent.fullname" . }}-{{ $i }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if or (.Values.config.playground) (not (hasPrefix "vci_sr_" .Values.config.virtualClusterID)) }}
    - port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
    {{- end }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if or (.Values.config.playground) (hasPrefix "vci_sr_" .Values.config.virtualClusterID) }}
    - port: {{ .Values.service.schemaRegistryPort | default 9094 }}
      targetPort: schema-registry
      protocol: TCP
      name: schema-registry
    {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "warpstream-agent.fullname" . }}-{{ $i }}
...
{{- end }}
{{- end }}
{{- end }}
{{- end }}
