config:
  playground: true
  
deploymentStrategy:
  type: RollingUpdate
  rollingUpdate: null # setting rollingUpdate to null so helm will fail if pod doesn't start

# overriding resources so it fits on a runner
resources:
  requests:
    cpu: 1
    memory: 4Gi
    # we do not need the disk space, but Kubernetes will count some logs that it emits
    # about our containers towards our containers ephemeral usage and if we requested
    # 0 storage we could end up getting evicted unnecessarily when the node is under disk pressure.
    ephemeral-storage: "100Mi"
  limits:
    memory: 4Gi