apiVersion: v2
name: warpstream-agent
description: WarpStream Agent for Kubernetes.
type: application
version: 0.13.7
appVersion: v570
icon: https://avatars.githubusercontent.com/u/132156278
home: https://docs.warpstream.com/warpstream/
sources:
  - https://github.com/warpstreamlabs/charts/warpstream-agent
